# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
#u[pdate

trigger:
- main

resources:
- repo: self

pool:
  name: project-pool 

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'f9975a12-2adb-465a-a9c1-83e85eabbfc5'
  containerregistrytype: 'Azure Container Registry'
  containerRegistry: 'ACR-connection'
  imageRepository: 'nginx'
  dockerfilePath: $(Build.SourcesDirectory)/Dockerfile
  tag: '$(Build.BuildId)'

# stages:
# - stage: Build
#   displayName: Build and push stage
#   jobs:
#   - job: Build
#     displayName: Build
#     steps:

    # - task: Docker@2
    #   displayName: push an image to container registry
    #   inputs:
    #     command: buildAndPush
    #     repository: $(imageRepository)
    #     dockerfile: $(dockerfilePath)
    #     containerRegistry: $(ContainerRegistry)
    #     tags: |
    #       $(tag)

    # - task: AzureCLI@2
    #   inputs:
    #     azureSubscription: 'service-azure'
    #     scriptType: 'bash'
    #     scriptLocation: 'inlineScript'
    #     inlineScript: |
    #       az container create \
    #         --name todoapp \
    #         --resource-group React \
    #         --image $(containerRegistry)/$(imageRepository):$(tag) \
    #         --registry-login-server $(containerRegistry) \
    #         --registry-username registrytestt  \
    #         --registry-password XXXX \

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(ContainerRegistry)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to Azure Container Instance
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'service-azure'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container create \
            --name todoapp \
            --resource-group React \
            --image $(containerRegistry)/$(imageRepository):$(tag) \
            --registry-login-server $(containerRegistry).azurecr.io \
            --registry-username registrytestt  \
            --registry-password XXXX \
